language: r
pandoc_version: 2.9.2.1
cache: 
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

## pandoc_version: 1.19.2.1

before_install:
  - chmod +x ./_build.sh
  - git config --global user.email "yiluheihei@gmail.com"
  - git config --global user.name "yiluheihei"

script:
  - ./_build.sh
  
branches:
  only:
    - master
  
after_success:
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git book-output
  - cd book-output
  - cp -r ../_book/* ./
  - git add --all *
  - git commit -m"Update the book" || true
  - git push -q origin gh-pages
