anguage: r
cache: 
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

## pandoc_version: 1.19.2.1

before_install:
  - chmod +x ./_build.sh
  - git config --global user.email "yiluheihei@gmail.com"
  - git config --global user.name "yiluheihei"

script:
  - ./_build.sh
  
branches:
  only:
    - master
  
after_success:
  - git add -A
  - git commit -m "update book"
  - git push -q https://${GITHUB_PAT}@github.com/yiluheihei/question.git HEAD:master
